import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { gzipSync } from "node:zlib";

import { build } from "esbuild";

import { buildClientBundle } from "../scripts/build-client.mjs";

const external = [
  "@getpaseo/plugin",
  "@getpaseo/plugin/*",
  "react",
  "react/*",
  "react-native",
  "zod",
];

async function hostCompile(entryPoint: string): Promise<Uint8Array> {
  const result = await build({
    bundle: true,
    entryPoints: [entryPoint],
    external,
    format: "cjs",
    jsx: "automatic",
    legalComments: "none",
    logLevel: "silent",
    platform: "neutral",
    target: "es2020",
    treeShaking: true,
    write: false,
  });
  assert.equal(result.outputFiles.length, 1);
  return result.outputFiles[0].contents;
}

async function timedHostCompile(entryPoint: string): Promise<{
  output: Uint8Array;
  durationMs: number;
}> {
  const started = performance.now();
  const output = await hostCompile(entryPoint);
  return { output, durationMs: performance.now() - started };
}

function median(values: number[]): number {
  const sorted = [...values].sort((left, right) => left - right);
  return sorted[Math.floor(sorted.length / 2)];
}

test("the generated client entry is current and keeps the Paseo boundary", async () => {
  const result = await buildClientBundle({ check: true });
  assert.equal(result.changed, false);
  const generated = readFileSync("client/generated-entry.js", "utf8");
  assert.match(generated, /^\/\/ Generated by npm run build:client\./);
  assert.match(generated, /export\{[^}]* as default\}/);
  assert.doesNotMatch(generated, /from["']\.\.?\//);
  assert.doesNotMatch(generated, /(?:from|import)\(?["']node:/);
});

test("the prebundle materially reduces Paseo's second-pass client payload", async (context) => {
  // Warm esbuild once for each graph, then alternate order so service startup
  // and filesystem cache effects do not systematically favor either entry.
  await hostCompile("client/plugin-entry.tsx");
  await hostCompile("index.client.tsx");
  const directDurations: number[] = [];
  const prebundledDurations: number[] = [];
  let direct: Uint8Array<ArrayBufferLike> = new Uint8Array();
  let prebundled: Uint8Array<ArrayBufferLike> = new Uint8Array();
  for (let index = 0; index < 7; index += 1) {
    const entries = index % 2 === 0
      ? ["client/plugin-entry.tsx", "index.client.tsx"]
      : ["index.client.tsx", "client/plugin-entry.tsx"];
    for (const entryPoint of entries) {
      const measured = await timedHostCompile(entryPoint);
      if (entryPoint === "client/plugin-entry.tsx") {
        direct = measured.output;
        directDurations.push(measured.durationMs);
      } else {
        prebundled = measured.output;
        prebundledDurations.push(measured.durationMs);
      }
    }
  }
  const directGzip = gzipSync(direct).byteLength;
  const prebundledGzip = gzipSync(prebundled).byteLength;
  const rawRatio = prebundled.byteLength / direct.byteLength;
  const gzipRatio = prebundledGzip / directGzip;
  const directMedianMs = median(directDurations);
  const prebundledMedianMs = median(prebundledDurations);

  context.diagnostic(JSON.stringify({
    directRawBytes: direct.byteLength,
    prebundledRawBytes: prebundled.byteLength,
    directGzipBytes: directGzip,
    prebundledGzipBytes: prebundledGzip,
    rawReduction: 1 - rawRatio,
    gzipReduction: 1 - gzipRatio,
    runs: directDurations.length,
    directMedianMs,
    prebundledMedianMs,
    medianCompileReduction: 1 - (prebundledMedianMs / directMedianMs),
  }));
  assert.ok(rawRatio < 0.75, `expected raw ratio below 0.75, got ${rawRatio}`);
  assert.ok(gzipRatio < 0.9, `expected gzip ratio below 0.9, got ${gzipRatio}`);
});

test("development and managed installs both rebuild the generated entry", () => {
  const manifest = JSON.parse(readFileSync("paseo-plugin.json", "utf8"));
  const packageJson = JSON.parse(readFileSync("package.json", "utf8"));
  assert.deepEqual(manifest.build, [
    ["npm", "ci", "--ignore-scripts"],
    ["npm", "run", "build:client"],
  ]);
  assert.equal(packageJson.scripts.prepare, "npm run build:client");
  assert.match(packageJson.scripts.reload, /npm run typecheck/);
  assert.match(packageJson.scripts.reload, /paseo plugin reload inline-review/);
});
