import { readFile, rename, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build, context } from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entryPoint = resolve(root, "client/plugin-entry.tsx");
const outputPath = resolve(root, "client/generated-entry.js");
const temporaryOutputPath = `${outputPath}.tmp`;
const external = [
  "@getpaseo/plugin",
  "@getpaseo/plugin/*",
  "react",
  "react/*",
  "react-native",
  "zod",
];

const buildOptions = {
  absWorkingDir: root,
  banner: {
    js: "// Generated by npm run build:client. Edit client/plugin-entry.tsx and its imports instead.",
  },
  bundle: true,
  charset: "utf8",
  entryPoints: [entryPoint],
  external,
  format: "esm",
  jsx: "automatic",
  legalComments: "none",
  logLevel: "warning",
  metafile: true,
  minify: true,
  platform: "neutral",
  target: "es2020",
  treeShaking: true,
};

function assertClientBoundary(result) {
  const unexpectedInputs = Object.keys(result.metafile.inputs).filter((input) => {
    const path = input.replaceAll("\\\\", "/");
    return !path.startsWith("client/") && !path.startsWith("shared/");
  });
  if (unexpectedInputs.length > 0) {
    throw new Error(`Client prebundle crossed its source boundary: ${unexpectedInputs.join(", ")}`);
  }

  const output = Object.values(result.metafile.outputs)[0];
  const unexpectedExternalImports = (output?.imports ?? [])
    .filter((dependency) => dependency.external)
    .map((dependency) => dependency.path)
    .filter((dependency) => !external.some((allowed) => (
      allowed.endsWith("/*")
        ? dependency.startsWith(allowed.slice(0, -1))
        : dependency === allowed
    )));
  if (unexpectedExternalImports.length > 0) {
    throw new Error(`Client prebundle has an unexpected runtime import: ${unexpectedExternalImports.join(", ")}`);
  }
}

async function renderClientBundle() {
  const result = await build({
    ...buildOptions,
    outfile: outputPath,
    write: false,
  });
  assertClientBoundary(result);
  const output = result.outputFiles?.find((file) => file.path === outputPath);
  if (!output) throw new Error("esbuild did not produce the client entry");
  return output.text;
}

async function currentOutput() {
  try {
    return await readFile(outputPath, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return null;
    throw error;
  }
}

export async function buildClientBundle({ check = false } = {}) {
  const generated = await renderClientBundle();
  const current = await currentOutput();
  if (generated === current) return { changed: false, bytes: Buffer.byteLength(generated) };
  if (check) {
    throw new Error(`${relative(root, outputPath)} is missing or stale; run npm run build:client`);
  }
  await writeFile(temporaryOutputPath, generated, "utf8");
  await rename(temporaryOutputPath, outputPath);
  return { changed: true, bytes: Buffer.byteLength(generated) };
}

async function watchClientBundle() {
  const rebuild = {
    name: "inline-review-atomic-output",
    setup(pluginBuild) {
      pluginBuild.onEnd(async (result) => {
        if (result.errors.length > 0 || !result.outputFiles) return;
        assertClientBoundary(result);
        const output = result.outputFiles.find((file) => file.path === outputPath);
        if (!output) return;
        const current = await currentOutput();
        if (current === output.text) return;
        await writeFile(temporaryOutputPath, output.text, "utf8");
        await rename(temporaryOutputPath, outputPath);
        process.stdout.write(`built ${relative(root, outputPath)} (${output.contents.byteLength} bytes)\n`);
      });
    },
  };
  const buildContext = await context({
    ...buildOptions,
    outfile: outputPath,
    plugins: [rebuild],
    write: false,
  });
  await buildContext.watch();
  process.stdout.write("watching client/ and shared/ for client prebundle changes\n");
}

const invokedDirectly = process.argv[1]
  && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (invokedDirectly) {
  if (process.argv.includes("--watch")) {
    await watchClientBundle();
  } else {
    const result = await buildClientBundle({ check: process.argv.includes("--check") });
    process.stdout.write(`${result.changed ? "built" : "current"} ${relative(root, outputPath)} (${result.bytes} bytes)\n`);
  }
}
